FROM node:16.13.0-alpine
WORKDIR /app/react

RUN npm install --save prop-types
RUN npm install -g create-react-app

RUN npm install --save react-router-dom
RUN npm install -g @types/react-router-dom
RUN npm install -g react-dev-utils
RUN npm install axios
RUN npm install swiper
RUN npm install react-bootstrap bootstrap@5.1.3
