FROM node:16.13.0-alpine
WORKDIR /app/react

RUN npm install --save prop-types
RUN npm install -g create-react-app

RUN npm install --save react-router-dom
RUN npm install --save-dev @types/react-router-dom
RUN npm install --save-dev react-dev-utils
RUN npm install axios
RUN npm install swiper
