version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_container
    # ports:
    #   - 80:80
    restart: always
    environment:
      - TZ=Asia/Tokyo

      # - VIRTUAL_HOST=localhost
      # - LETSENCRYPT_HOST=localhost
      # - LETSENCRYPT_EMAIL=bdkouiti5013@gmail.com # Let's Encryptのメール設定
      # - LETSENCRYPT_TEST=true # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
      # - CERT_NAME=default # ローカルで認証局を立てるときに使う ※本番ではLet's Encryptから直接取得するのでコメントアウトする
      # - HTTPS_METHOD=noredirect # リダイレクトを無効にする

      - VIRTUAL_HOST=maman2030-himeji.com,www.maman2030-himeji.com # nginx-proxyのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - LETSENCRYPT_HOST=maman2030-himeji.com,www.maman2030-himeji.com # Let's Encryptのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - LETSENCRYPT_EMAIL=bdkouiti5013@gmail.com # Let's Encryptのメール設定
      - LETSENCRYPT_TEST=false # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - container-link

  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: react_container
    restart: always
    tty: true
    volumes:
      - ./react-app:/app/react
    command: sh -c "cd /app/react/react-app && yarn start"
    ports:
      - 3000:3000
    networks:
      - container-link


  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paswd
      MYSQL_DATABASE: go_database
      MYSQL_USER: user
      MYSQL_PASSWORD: paswd
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    links:
      - go
    networks:
      - container-link


  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    restart: always
    environment:
      MYSQL_DATABASE: go_database
      MYSQL_HOST: mysql_container
      MYSQL_USER: user
      MYSQL_PASSWORD: paswd
    volumes:
      - ./go-app/images:/go/src/go-app/images
    networks:
      - container-link


  phpmyadmin:
    build:
      context: .
      dockerfile: ./docker/phpadmin/Dockerfile
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=paswd
    links:
      - mysql
    ports:
      - 1234:80
    volumes:
      - /sessions
    networks:
      - container-link


networks:
  default:
    external:
      name: bridge
  container-link:
    name: container_network
